/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.aluno.pdss8.mesa;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author PABLO DANIEL
 */
public class MesaGUI extends javax.swing.JFrame {

    /**
     * Creates new form MesaGUI
     */
    private DefaultListModel<Mesa> modelMesa;
    private MesaRepository repository;
    
    public MesaGUI() {
        repository = new MesaRepository();  // inicialize primeiro!
        modelMesa = new DefaultListModel<>();
        modelMesa.addAll(repository.findAll());
        initComponents();
        lblAlerta.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCapacidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNmesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOcupada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ParaLixeira = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        Excluidos = new javax.swing.JRadioButton();
        naoExcluidos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListMesa = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Capacidade:");

        txtCapacidade.setText("Digite a capacidade");

        jLabel2.setText("Numero da mesa:");

        txtNmesa.setText("Digite o numero da Mesa");

        jLabel3.setText("Ocupada:");

        txtOcupada.setText("\"ocupada\" ou \"livre\"");

        jLabel6.setText("Lugar:");

        txtLugar.setText("Digite o nome da área");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCapacidade)
                            .addComponent(txtNmesa, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtOcupada)
                            .addComponent(txtLugar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNmesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtOcupada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Cadastro", jPanel2);

        ParaLixeira.setText("Mover para Lixeira");
        ParaLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaLixeiraActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        buttonGroup1.add(Excluidos);
        Excluidos.setText("Excluidos");
        Excluidos.setOpaque(true);
        Excluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ExcluidosItemStateChanged(evt);
            }
        });

        buttonGroup1.add(naoExcluidos);
        naoExcluidos.setSelected(true);
        naoExcluidos.setText("Não Excluídos");
        naoExcluidos.setOpaque(true);
        naoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                naoExcluidosItemStateChanged(evt);
            }
        });

        ListMesa.setModel(modelMesa);
        jScrollPane1.setViewportView(ListMesa);

        jLabel4.setText("Lista de Mesas");

        jLabel5.setText("L:ixeira");

        lblAlerta.setBackground(new java.awt.Color(255, 204, 0));
        lblAlerta.setForeground(new java.awt.Color(255, 51, 0));
        lblAlerta.setText("Escolha uma Mesa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAlerta)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naoExcluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Excluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ParaLixeira)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Excluidos)
                        .addGap(5, 5, 5)
                        .addComponent(naoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ParaLixeira)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEsvaziar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblAlerta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
           repository = new MesaRepository();
            String numero = txtNmesa.getText();
            String capacidade = txtCapacidade.getText();
            String ocupada = txtOcupada.getText();
            String lugar = txtLugar.getText();
            Mesa m1 = new Mesa();
            m1.setLocalizacao(lugar);
            m1.setNumero(Integer.parseInt(numero));
            m1.setCapacidade(Integer.parseInt(capacidade));
            m1.setOcupada(ocupada);

            repository.saveOrUpdate(m1);
            clearFields();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void ParaLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaLixeiraActionPerformed
        if (ListMesa.getSelectedIndices().length == 0) {
            showWarning("Selecione ao menos um item");
        }
        if (ListMesa.getSelectedIndices().length == 1) {
            Mesa selected = ListMesa.getSelectedValue();
            repository.moverParaLixeira(selected);
            modelMesa.removeElement(selected);
        } else {
            List<Mesa> selection = ListMesa.getSelectedValuesList();
            repository.moverParaLixeira(selection);
            for (Mesa m : selection) {
                modelMesa.removeElement(m);
            }
        }
    }//GEN-LAST:event_ParaLixeiraActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if (ListMesa.getSelectedIndices().length == 0) {
            showWarning("Selecione um item");
        }
        if (ListMesa.getSelectedIndices().length == 1) {
            Mesa selected = ListMesa.getSelectedValue();
            repository.restaurar(selected);
            modelMesa.removeElement(selected);
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (ListMesa.getSelectedIndices().length == 0) {
            showWarning("Selecione um item");
            if (ListMesa.getSelectedIndices().length == 1) {
                Mesa selected = ListMesa.getSelectedValue();
                repository.excluirDefinitivamente(selected);
                modelMesa.removeElement(selected);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
        
    private void ExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ExcluidosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            atualizarBotoes(false);
            modelMesa.clear();
            modelMesa.addAll(repository.buscarTodosNaLixeira()); 
            }  
    }//GEN-LAST:event_ExcluidosItemStateChanged

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        repository.esvaziarLixeira();
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void naoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_naoExcluidosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            atualizarBotoes(true);
            modelMesa.clear();
            modelMesa.addAll(repository.findAll());  // Carrega os não excluídos
        }    }//GEN-LAST:event_naoExcluidosItemStateChanged
    
    private void atualizarBotoes(boolean status) {
        ParaLixeira.setEnabled(status);
        btnExcluir.setEnabled(!status);
        btnRestaurar.setEnabled(!status);
        btnEsvaziar.setEnabled(!status);
    }
    
    private void showWarning(String warning) {
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
        
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    private void clearFields() {
        txtLugar.setText(null);
        txtOcupada.setText(null);
        txtCapacidade.setText(null);
        txtNmesa.setText(null);
        txtNmesa.requestFocus();
        txtCapacidade.requestFocus();
        txtLugar.requestFocus();
        txtOcupada.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Excluidos;
    private javax.swing.JList<Mesa> ListMesa;
    private javax.swing.JButton ParaLixeira;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JRadioButton naoExcluidos;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNmesa;
    private javax.swing.JTextField txtOcupada;
    // End of variables declaration//GEN-END:variables
}
