/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.aluno.pdss8.funcionario;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author PABLO DANIEL
 */
public class FuncionarioGUI extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioGUI
     */
    
    private DefaultListModel<Funcionario> modelFuncionario;
    private FuncionarioRepository repository;
    
    public FuncionarioGUI() {
        repository = new FuncionarioRepository();
        modelFuncionario = new DefaultListModel<>();
        modelFuncionario.addAll(repository.findAll());
        initComponents();
        
        lblAlerta.setVisible(false); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        JanelaCadastro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListFuncionarios = new javax.swing.JList<>();
        Excluidos = new javax.swing.JRadioButton();
        NãoExcluidos = new javax.swing.JRadioButton();
        Excluir = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();
        ParaLixeira = new javax.swing.JButton();
        panelCadastro = new javax.swing.JPanel();
        LabelNome = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Lista de Funcionários");

        ListFuncionarios.setModel(modelFuncionario);
        jScrollPane1.setViewportView(ListFuncionarios);

        buttonGroup1.add(Excluidos);
        Excluidos.setSelected(true);
        Excluidos.setText("Excluídos");
        Excluidos.setOpaque(true);
        Excluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ExcluidosItemStateChanged(evt);
            }
        });
        Excluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluidosActionPerformed(evt);
            }
        });

        buttonGroup1.add(NãoExcluidos);
        NãoExcluidos.setText("Não Excluídos");
        NãoExcluidos.setOpaque(true);
        NãoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NãoExcluidosItemStateChanged(evt);
            }
        });
        NãoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NãoExcluidosActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar lixeira");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        jLabel5.setText("Lixeira:");

        lblAlerta.setBackground(new java.awt.Color(255, 204, 51));
        lblAlerta.setForeground(new java.awt.Color(255, 51, 51));
        lblAlerta.setText("Selecione um Funcionário");

        ParaLixeira.setText("Mover Para Lixeira");
        ParaLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaLixeiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Excluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NãoExcluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Excluir, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(24, 24, 24))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(107, 107, 107)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ParaLixeira)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAlerta))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Excluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NãoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(ParaLixeira)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEsvaziar)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        JanelaCadastro.addTab("Listagem", jPanel2);

        LabelNome.setText("Nome:");

        LabelCPF.setText("CPF:");

        txtNome.setText("DIGITE O NOME ");

        txtCpf.setText("XXX.XXX.XXX-XX");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtCpf)))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCPF)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(27, 27, 27))
        );

        JanelaCadastro.addTab("Cadastro", panelCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JanelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JanelaCadastro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if (ListFuncionarios.getSelectedIndices().length == 0) {
            showWarning("Selecione um item");
        }
        if (ListFuncionarios.getSelectedIndices().length == 1) {
            Funcionario selected = ListFuncionarios.getSelectedValue();
            repository.restaurar(selected);
            modelFuncionario.removeElement(selected);
        }

    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if (ListFuncionarios.getSelectedIndices().length == 0) {
            showWarning("Selecione um item");
        if (ListFuncionarios.getSelectedIndices().length == 1) {
            Funcionario selected = ListFuncionarios.getSelectedValue();
            repository.excluirDefinitivamente(selected);
            modelFuncionario.removeElement(selected);
        } }
       
    }//GEN-LAST:event_ExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        repository = new FuncionarioRepository();
        String nome = txtNome.getText();
        String CPF = txtCpf.getText();

        Funcionario f1 = new Funcionario();
        f1.setNome(nome);
        f1.setCpf(CPF);

        repository.saveOrUpdate(f1);
        clearFields();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        repository.esvaziarLixeira();
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void ParaLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaLixeiraActionPerformed
        if (ListFuncionarios.getSelectedIndices().length == 0) {
            showWarning("Selecione ao menos um item");
        }
        if (ListFuncionarios.getSelectedIndices().length == 1) {
            Funcionario selected = ListFuncionarios.getSelectedValue();
            repository.moverParaLixeira(selected);
            modelFuncionario.removeElement(selected);
        } else {
            List<Funcionario> selection = ListFuncionarios.getSelectedValuesList();
            repository.moverParaLixeira(selection);
            for (Funcionario f : selection) {
                modelFuncionario.removeElement(f);
            }
        }
    }//GEN-LAST:event_ParaLixeiraActionPerformed

    private void ExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ExcluidosItemStateChanged

           if (evt.getStateChange() == ItemEvent.SELECTED) {
            atualizarBotoes(false);
            modelFuncionario.clear();
            modelFuncionario.addAll(repository.buscarTodosNaLixeira()); 
            }//GEN-LAST:event_ExcluidosItemStateChanged
    }
    private void NãoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NãoExcluidosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
        atualizarBotoes(true);
        modelFuncionario.clear();
        modelFuncionario.addAll(repository.findAll());  // Carrega os não excluídos
    }
    }//GEN-LAST:event_NãoExcluidosItemStateChanged

    private void ExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluidosActionPerformed

    private void NãoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NãoExcluidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NãoExcluidosActionPerformed
    
    private void atualizarBotoes(boolean status) {
        ParaLixeira.setEnabled(status);
        Excluir.setEnabled(!status);
        btnRestaurar.setEnabled(!status);
        btnEsvaziar.setEnabled(!status);
    }
    
    private void showWarning(String warning) {
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
        
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    private void clearFields() {
        txtNome.setText(null);
        txtCpf.setText(null);
        txtNome.requestFocus();
        txtCpf.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Excluidos;
    private javax.swing.JButton Excluir;
    private javax.swing.JTabbedPane JanelaCadastro;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JList<Funcionario> ListFuncionarios;
    private javax.swing.JRadioButton NãoExcluidos;
    private javax.swing.JButton ParaLixeira;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
