/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.aluno.pdss8.cardapio;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author IFNMG
 */
public class ItemCardapioGUI extends javax.swing.JFrame {

    private DefaultListModel<ItemCardapio> modelCardapio;
    private ItemCardapioRepository repository;

    /**
     * Creates new form NewJFrame
     */
    public ItemCardapioGUI() {

        repository = new ItemCardapioRepository();
        modelCardapio = new DefaultListModel<>();
        modelCardapio.addAll(repository.findAll());

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jlbNome = new javax.swing.JLabel();
        jlbPreco = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        pnlListagem = new javax.swing.JPanel();
        btnParaLixeira = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        jlbLixeira = new javax.swing.JLabel();
        radAtivos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        jlbCardapio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCardapio = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Item");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jlbNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbNome.setText("Nome do Produto:");

        jlbPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPreco.setText("Preço do Produto:");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addComponent(jlbPreco)
                        .addGap(25, 25, 25)
                        .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addComponent(jlbNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome)))
                .addContainerGap())
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnSalvar)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Cadastro", pnlCadastro);

        btnParaLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnParaLixeira.setText("Mover para a Lixeira");
        btnParaLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaLixeiraActionPerformed(evt);
            }
        });

        btnRestaurar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEsvaziar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEsvaziar.setText("Esvaziar Lixeira");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        jlbLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbLixeira.setText("Lixeira:");

        buttonGroup1.add(radAtivos);
        radAtivos.setSelected(true);
        radAtivos.setText("Não Excluídos");
        radAtivos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radAtivosItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radExcluidos);
        radExcluidos.setText("Excluídos");
        radExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radExcluidosItemStateChanged(evt);
            }
        });

        jlbCardapio.setText("Cardápio");

        lstCardapio.setModel(modelCardapio);
        jScrollPane2.setViewportView(lstCardapio);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCardapio)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnParaLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbLixeira)
                    .addComponent(radAtivos)
                    .addComponent(radExcluidos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radAtivos)
                    .addComponent(jlbCardapio))
                .addGap(3, 3, 3)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParaLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jlbLixeira)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addGap(7, 7, 7)
                        .addComponent(btnEsvaziar)
                        .addGap(9, 9, 9))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        repository = new ItemCardapioRepository();
        String nome = txtNome.getText();
        double preco = Double.parseDouble(txtPreco.getText());

        ItemCardapio i1 = new ItemCardapio();
        i1.setNome(nome);
        i1.setPreco(preco);

        repository.saveOrUpdate(i1);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnParaLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaLixeiraActionPerformed

        if (lstCardapio.getSelectedIndices().length == 0) {

        }
        if (lstCardapio.getSelectedIndices().length == 1) {
            ItemCardapio selected = lstCardapio.getSelectedValue();
            repository.moverParaLixeira(selected);
            modelCardapio.removeElement(selected);
        } else {
            List<ItemCardapio> selection = lstCardapio.getSelectedValuesList();
            repository.moverParaLixeira(selection);
            for (ItemCardapio i : selection) {
                modelCardapio.removeElement(i);
            }
        }

    }//GEN-LAST:event_btnParaLixeiraActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if (lstCardapio.getSelectedIndices().length == 0) {

        }
        if (lstCardapio.getSelectedIndices().length == 1) {
            ItemCardapio selected = lstCardapio.getSelectedValue();
            repository.restaurar(selected);
            modelCardapio.removeElement(selected);
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (lstCardapio.getSelectedIndices().length == 0) {

        }
        if (lstCardapio.getSelectedIndices().length == 1) {
            ItemCardapio selected = lstCardapio.getSelectedValue();
            repository.excluirDefinitivamente(selected);
            modelCardapio.removeElement(selected);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        repository.esvaziarLixeira();
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void radAtivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radAtivosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            atualizarBotoes(true);
            modelCardapio.clear();
            modelCardapio.addAll(repository.findAll());
        }
    }//GEN-LAST:event_radAtivosItemStateChanged

    private void radExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radExcluidosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            atualizarBotoes(false);
            modelCardapio.clear();
            modelCardapio.addAll(repository.buscarTodosNaLixeira());
        }
    }//GEN-LAST:event_radExcluidosItemStateChanged

    private void atualizarBotoes(boolean status) {
        btnParaLixeira.setEnabled(status);
        btnExcluir.setEnabled(!status);
        btnRestaurar.setEnabled(!status);
        btnEsvaziar.setEnabled(!status);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemCardapioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemCardapioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemCardapioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemCardapioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemCardapioGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnParaLixeira;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbCardapio;
    private javax.swing.JLabel jlbLixeira;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbPreco;
    private javax.swing.JList<ItemCardapio> lstCardapio;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radAtivos;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
